// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsq3nTl3rksYTQAIGpFRx3VNW2M_rmz_M',
    appId: '1:610149107217:web:95c8361077ac82442a93b0',
    messagingSenderId: '610149107217',
    projectId: 'inv-management-project-darsh',
    authDomain: 'inv-management-project-darsh.firebaseapp.com',
    storageBucket: 'inv-management-project-darsh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULNz48FKWDZ09NVEbXKvttIfXNg-HRHk',
    appId: '1:610149107217:android:dad5a50527abdab72a93b0',
    messagingSenderId: '610149107217',
    projectId: 'inv-management-project-darsh',
    storageBucket: 'inv-management-project-darsh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBGNRZTn1vne6Eh-YDTi4wTKDl20aPDTA',
    appId: '1:610149107217:ios:30e18692c85ee2092a93b0',
    messagingSenderId: '610149107217',
    projectId: 'inv-management-project-darsh',
    storageBucket: 'inv-management-project-darsh.firebasestorage.app',
    iosBundleId: 'com.example.invManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBGNRZTn1vne6Eh-YDTi4wTKDl20aPDTA',
    appId: '1:610149107217:ios:30e18692c85ee2092a93b0',
    messagingSenderId: '610149107217',
    projectId: 'inv-management-project-darsh',
    storageBucket: 'inv-management-project-darsh.firebasestorage.app',
    iosBundleId: 'com.example.invManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsq3nTl3rksYTQAIGpFRx3VNW2M_rmz_M',
    appId: '1:610149107217:web:4be2fe2ffe19449e2a93b0',
    messagingSenderId: '610149107217',
    projectId: 'inv-management-project-darsh',
    authDomain: 'inv-management-project-darsh.firebaseapp.com',
    storageBucket: 'inv-management-project-darsh.firebasestorage.app',
  );

}